import type { ItemDefinition } from '@/typings/pet'

export const PET_ITEM_CATALOG: ItemDefinition[] = [
  // --- Food (5 items) ---
  {
    id: 'food_bread',
    name: '面包',
    icon: '🍞',
    type: 'food',
    effect: { stat: 'hunger', value: 20 },
    price: 8,
    rarity: 'common',
    unlockLevel: 0,
    description: '普通面包，填饱肚子',
  },
  {
    id: 'food_apple',
    name: '苹果',
    icon: '🍎',
    type: 'food',
    effect: { stat: 'hunger', value: 25 },
    price: 12,
    rarity: 'common',
    unlockLevel: 0,
    description: '新鲜苹果，香甜可口',
  },
  {
    id: 'food_fish',
    name: '小鱼干',
    icon: '🐟',
    type: 'food',
    effect: { stat: 'hunger', value: 30 },
    price: 15,
    rarity: 'common',
    unlockLevel: 2,
    description: '猫咪最爱的小鱼干',
  },
  {
    id: 'food_cake',
    name: '蛋糕',
    icon: '🎂',
    type: 'food',
    effect: { stat: 'hunger', value: 40 },
    price: 20,
    rarity: 'rare',
    unlockLevel: 5,
    description: '美味蛋糕，大幅增加饱食度',
  },
  {
    id: 'food_milk',
    name: '牛奶',
    icon: '🥛',
    type: 'food',
    effect: { stat: 'mood', value: 10 },
    price: 10,
    rarity: 'common',
    unlockLevel: 0,
    description: '温热牛奶，让宠物心情愉快',
  },

  // --- Toys (4 items) ---
  {
    id: 'toy_ball',
    name: '毛线球',
    icon: '🧶',
    type: 'toy',
    effect: { stat: 'mood', value: 20 },
    price: 15,
    rarity: 'common',
    unlockLevel: 0,
    description: '猫咪最爱的毛线球',
  },
  {
    id: 'toy_feather',
    name: '羽毛棒',
    icon: '🪶',
    type: 'toy',
    effect: { stat: 'mood', value: 15 },
    price: 12,
    rarity: 'common',
    unlockLevel: 0,
    description: '轻盈的羽毛棒，逗猫必备',
  },
  {
    id: 'toy_puzzle',
    name: '益智玩具',
    icon: '🧩',
    type: 'toy',
    effect: { stat: 'mood', value: 35 },
    price: 25,
    rarity: 'rare',
    unlockLevel: 5,
    description: '智力玩具，大幅提升心情和经验',
  },
  {
    id: 'toy_musicbox',
    name: '音乐盒',
    icon: '🎵',
    type: 'toy',
    effect: { stat: 'mood', value: 25 },
    price: 20,
    rarity: 'rare',
    unlockLevel: 3,
    description: '悦耳的音乐盒，让宠物心情大好',
  },

  // --- Cleaning (3 items) ---
  {
    id: 'clean_soap',
    name: '香皂',
    icon: '🧼',
    type: 'cleaning',
    effect: { stat: 'cleanliness', value: 25 },
    price: 10,
    rarity: 'common',
    unlockLevel: 0,
    description: '普通香皂，清洁干净',
  },
  {
    id: 'clean_brush',
    name: '梳子',
    icon: '🪮',
    type: 'cleaning',
    effect: { stat: 'cleanliness', value: 35 },
    price: 15,
    rarity: 'common',
    unlockLevel: 2,
    description: '专业梳子，让毛发顺滑',
  },
  {
    id: 'clean_bathbomb',
    name: '沐浴球',
    icon: '🫧',
    type: 'cleaning',
    effect: { stat: 'cleanliness', value: 50 },
    price: 25,
    rarity: 'rare',
    unlockLevel: 5,
    description: '豪华沐浴球，全身清洁焕然一新',
  },

  // --- Decorations (3 items) ---
  {
    id: 'deco_ribbon',
    name: '蝴蝶结',
    icon: '🎀',
    type: 'decoration',
    effect: { stat: 'decoration', decorationId: 'ribbon' },
    price: 50,
    rarity: 'common',
    unlockLevel: 5,
    description: '可爱的蝴蝶结，让宠物更漂亮',
  },
  {
    id: 'deco_hat',
    name: '小帽子',
    icon: '🎩',
    type: 'decoration',
    effect: { stat: 'decoration', decorationId: 'hat' },
    price: 100,
    rarity: 'rare',
    unlockLevel: 10,
    description: '帅气的小帽子，绅士风范',
  },
  {
    id: 'deco_scarf',
    name: '围巾',
    icon: '🧣',
    type: 'decoration',
    effect: { stat: 'decoration', decorationId: 'scarf' },
    price: 80,
    rarity: 'rare',
    unlockLevel: 8,
    description: '温暖的围巾，冬日必备',
  },
]

export const ITEM_MAP = new Map(PET_ITEM_CATALOG.map((item) => [item.id, item]))

export const RARITY_COLORS: Record<string, string> = {
  common: 'text-gray-500 bg-gray-100 dark:text-gray-400 dark:bg-gray-700',
  rare: 'text-blue-600 bg-blue-100 dark:text-blue-400 dark:bg-blue-900/30',
  epic: 'text-purple-600 bg-purple-100 dark:text-purple-400 dark:bg-purple-900/30',
}

export const RARITY_LABELS: Record<string, string> = {
  common: '普通',
  rare: '稀有',
  epic: '史诗',
}
